# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goneat_simplesso_scan_location_flag.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='goneat_simplesso_scan_location_flag.proto',
  package='goneat_simplesso_scan_location_flag',
  serialized_pb='\n)goneat_simplesso_scan_location_flag.proto\x12#goneat_simplesso_scan_location_flag\"3\n\tFieldInfo\x12\x11\n\tbytes_key\x18\x01 \x01(\x0c\x12\x13\n\x0b\x62ytes_value\x18\x02 \x01(\x0c\"\x95\x01\n\x07ReqBody\x12\x14\n\x0c\x62ytes_rowkey\x18\x01 \x01(\x0c\x12\x13\n\x0buint32_rank\x18\x02 \x01(\r\x12J\n\x12rpt_msg_field_info\x18\x03 \x03(\x0b\x32..goneat_simplesso_scan_location_flag.FieldInfo\x12\x13\n\x0buint64_time\x18\x04 \x01(\x04\"\xbe\x01\n\x07RspBody\x12>\n\x08\x65num_ret\x18\x01 \x01(\x0e\x32,.goneat_simplesso_scan_location_flag.RetEnum\x12\x11\n\tbytes_msg\x18\x02 \x01(\x0c\x12\x14\n\x0c\x62ytes_rowkey\x18\x03 \x01(\x0c\x12J\n\x12rpt_msg_field_info\x18\x04 \x03(\x0b\x32..goneat_simplesso_scan_location_flag.FieldInfo*$\n\x0bSERVICE_CMD\x12\x15\n\x11\x43MD_Scan_Location\x10\x01*\xb0\x01\n\x07RetEnum\x12\x08\n\x04SUCC\x10\x00\x12\x16\n\x12\x46\x41IL_PARSE_REQ_PKG\x10@\x12\x19\n\x15REQ_PKG_PARAM_INVALID\x10\x41\x12\x17\n\x13REQ_MUST_PARAM_MISS\x10\x42\x12\x11\n\rSVR_INNER_ERR\x10\x43\x12\x11\n\rFAIL_BACK_SVR\x10\x44\x12\x15\n\x11\x46\x41IL_PACK_RSP_PKG\x10\x45\x12\x12\n\rSVR_OVER_LOAD\x10\x81\x01\x32\x91\x01\n#goneat_simplesso_scan_location_flag\x12j\n\x0cScanLocation\x12,.goneat_simplesso_scan_location_flag.ReqBody\x1a,.goneat_simplesso_scan_location_flag.RspBody')

_SERVICE_CMD = _descriptor.EnumDescriptor(
  name='SERVICE_CMD',
  full_name='goneat_simplesso_scan_location_flag.SERVICE_CMD',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_Scan_Location', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=480,
  serialized_end=516,
)

SERVICE_CMD = enum_type_wrapper.EnumTypeWrapper(_SERVICE_CMD)
_RETENUM = _descriptor.EnumDescriptor(
  name='RetEnum',
  full_name='goneat_simplesso_scan_location_flag.RetEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL_PARSE_REQ_PKG', index=1, number=64,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQ_PKG_PARAM_INVALID', index=2, number=65,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQ_MUST_PARAM_MISS', index=3, number=66,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_INNER_ERR', index=4, number=67,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL_BACK_SVR', index=5, number=68,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL_PACK_RSP_PKG', index=6, number=69,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVR_OVER_LOAD', index=7, number=129,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=519,
  serialized_end=695,
)

RetEnum = enum_type_wrapper.EnumTypeWrapper(_RETENUM)
CMD_Scan_Location = 1
SUCC = 0
FAIL_PARSE_REQ_PKG = 64
REQ_PKG_PARAM_INVALID = 65
REQ_MUST_PARAM_MISS = 66
SVR_INNER_ERR = 67
FAIL_BACK_SVR = 68
FAIL_PACK_RSP_PKG = 69
SVR_OVER_LOAD = 129



_FIELDINFO = _descriptor.Descriptor(
  name='FieldInfo',
  full_name='goneat_simplesso_scan_location_flag.FieldInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes_key', full_name='goneat_simplesso_scan_location_flag.FieldInfo.bytes_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='goneat_simplesso_scan_location_flag.FieldInfo.bytes_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=133,
)


_REQBODY = _descriptor.Descriptor(
  name='ReqBody',
  full_name='goneat_simplesso_scan_location_flag.ReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes_rowkey', full_name='goneat_simplesso_scan_location_flag.ReqBody.bytes_rowkey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_rank', full_name='goneat_simplesso_scan_location_flag.ReqBody.uint32_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpt_msg_field_info', full_name='goneat_simplesso_scan_location_flag.ReqBody.rpt_msg_field_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64_time', full_name='goneat_simplesso_scan_location_flag.ReqBody.uint64_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=285,
)


_RSPBODY = _descriptor.Descriptor(
  name='RspBody',
  full_name='goneat_simplesso_scan_location_flag.RspBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum_ret', full_name='goneat_simplesso_scan_location_flag.RspBody.enum_ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_msg', full_name='goneat_simplesso_scan_location_flag.RspBody.bytes_msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes_rowkey', full_name='goneat_simplesso_scan_location_flag.RspBody.bytes_rowkey', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpt_msg_field_info', full_name='goneat_simplesso_scan_location_flag.RspBody.rpt_msg_field_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=288,
  serialized_end=478,
)

_REQBODY.fields_by_name['rpt_msg_field_info'].message_type = _FIELDINFO
_RSPBODY.fields_by_name['enum_ret'].enum_type = _RETENUM
_RSPBODY.fields_by_name['rpt_msg_field_info'].message_type = _FIELDINFO
DESCRIPTOR.message_types_by_name['FieldInfo'] = _FIELDINFO
DESCRIPTOR.message_types_by_name['ReqBody'] = _REQBODY
DESCRIPTOR.message_types_by_name['RspBody'] = _RSPBODY

class FieldInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIELDINFO

  # @@protoc_insertion_point(class_scope:goneat_simplesso_scan_location_flag.FieldInfo)

class ReqBody(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQBODY

  # @@protoc_insertion_point(class_scope:goneat_simplesso_scan_location_flag.ReqBody)

class RspBody(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RSPBODY

  # @@protoc_insertion_point(class_scope:goneat_simplesso_scan_location_flag.RspBody)


# @@protoc_insertion_point(module_scope)
